name: Build and Deploy Application
on:
  push:
    branches:
      - feature/change-message
jobs:
  Test-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow called!"
      - run: echo "Event that triggered this workflow was ${{ github.event_name }}"